Number = int(input('Informe um número pa ver sua tabuada: '))
print('============')
print(Number, 'X  1 = {}'.format(Number * 1))
print(Number, 'X  2 = {}'.format(Number * 2))
print(Number, 'X  3 = {}'.format(Number * 3))
print(Number, 'X  5 = {}'.format(Number * 5))
print(Number, 'X  6 = {}'.format(Number * 6))
print(Number, 'X  7 = {}'.format(Number * 7))
print(Number, 'X  8 = {}'.format(Number * 8))
print(Number, 'X  9 = {}'.format(Number * 9))
print(Number, 'X 10 = {}'.format(Number * 10))
print('============')
